name: Code Formatting

on: [push, pull_request]

jobs:
  black-formatting:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Format code
        uses: psf/black@stable
        with: 
          options: "app.py"

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Black Formatting
          commit_user_name: Black
